insert into category(id, name) values(1, 'spring');
insert into category(id, name) values(2, 'java');

insert into post(id, title, content, status, category_id) values(1, '테스트01', '지금 포스팅은 테스트 포스팅01 입니다.', 0, 1);
insert into post(id, title, content, status, category_id) values(2, '테스트02', '지금 포스팅은 테스트 포스팅02 입니다.', 0, 2);
insert into post(id, title, content, status, category_id) values(3, '테스트03', '지금 포스팅은 테스트 포스팅03 입니다.', 0, 1);
insert into post(id, title, content, status, category_id) values(4, '테스트04', '지금 포스팅은 테스트 포스팅04 입니다.', 0, 2);
insert into post(id, title, content, status, category_id) values(5, '테스트05', '지금 포스팅은 테스트 포스팅05 입니다.', 0, 1);
insert into post(id, title, content, status, category_id) values(6, '테스트06', '지금 포스팅은 테스트 포스팅06 입니다.', 0, 2);
insert into post(id, title, content, status, category_id) values(7, '테스트07', '지금 포스팅은 테스트 포스팅07 입니다.', 0, 1);
insert into post(id, title, content, status, category_id) values(8, '테스트08', '지금 포스팅은 테스트 포스팅08 입니다.', 0, 2);
insert into post(id, title, content, status, category_id) values(9, '테스트09', '지금 포스팅은 테스트 포스팅09 입니다.', 0, 1);
insert into post(id, title, content, status, category_id) values(10, '테스트10', '지금 포스팅은 테스트 포스팅10 입니다.', 0, 2);
insert into post(id, title, content, status, category_id) values(11, '테스트11', '지금 포스팅은 테스트 포스팅11 입니다.', 0, 1);
insert into post(id, title, content, status, category_id) values(12, '테스트12', '지금 포스팅은 테스트 포스팅12 입니다.', 0, 2);
insert into post(id, title, content, status, category_id) values(13, '테스트13', '지금 포스팅은 테스트 포스팅13 입니다.', 0, 1);
insert into post(id, title, content, status, category_id) values(14, '테스트14', '지금 포스팅은 테스트 포스팅14 입니다.', 0, 2);
insert into post(id, title, content, status, category_id) values(15, '테스트15', '지금 포스팅은 테스트 포스팅15 입니다.', 0, 1);
insert into post(id, title, content, status, category_id) values(16, '테스트16', '지금 포스팅은 테스트 포스팅16 입니다.', 0, 2);
insert into post(id, title, content, status, category_id) values(17, '테스트17', '지금 포스팅은 테스트 포스팅17 입니다.', 0, 1);
insert into post(id, title, content, status, category_id) values(18, '테스트18', '지금 포스팅은 테스트 포스팅18 입니다.', 0, 2);
insert into post(id, title, content, status, category_id) values(19, '테스트19', '지금 포스팅은 테스트 포스팅19 입니다.', 0, 1);
insert into post(id, title, content, status, category_id) values(20, '테스트20', '지금 포스팅은 테스트 포스팅20 입니다.', 0, 2);
insert into post(id, title, content, status, category_id) values(21, '테스트21', '지금 포스팅은 테스트 포스팅21 입니다.', 0, 1);
insert into post(id, title, content, status, category_id) values(22, '테스트22', '지금 포스팅은 테스트 포스팅22 입니다.', 0, 2);
insert into post(id, title, content, status, category_id) values(23, '테스트23', '지금 포스팅은 테스트 포스팅23 입니다.', 0, 1);
insert into post(id, title, content, status, category_id) values(24, '테스트24', '지금 포스팅은 테스트 포스팅24 입니다.', 0, 2);
insert into post(id, title, content, status, category_id) values(25, '테스트25', '지금 포스팅은 테스트 포스팅25 입니다.', 0, 1);
insert into post(id, title, content, status, category_id) values(26, '테스트26', '지금 포스팅은 테스트 포스팅26 입니다.', 0, 2);
insert into post(id, title, content, status, category_id) values(27, '테스트27', '지금 포스팅은 테스트 포스팅27 입니다.', 0, 1);
insert into post(id, title, content, status, category_id) values(28, '테스트28', '지금 포스팅은 테스트 포스팅28 입니다.', 0, 2);
insert into post(id, title, content, status, category_id) values(29, '테스트29', '지금 포스팅은 테스트 포스팅29 입니다.', 0, 1);
insert into post(id, title, content, status, category_id) values(30, '테스트30', '지금 포스팅은 테스트 포스팅30 입니다.', 0, 2);
insert into post(id, title, content, status, category_id) values(31, '테스트31', '지금 포스팅은 테스트 포스팅31 입니다.', 0, 1);
insert into post(id, title, content, status, category_id) values(32, '테스트32', '지금 포스팅은 테스트 포스팅32 입니다.', 0, 2);